config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile


  root 'challenges#index'

  get '/challenges/:id/challenger', to: 'challenges#challenger', as: 'challenger'

  resources :challenges do
    resources :comments
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord

  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :user_id, presence: true

  paginates_per  8

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
end

app/models/user.rb
class User < ApplicationRecord

  has_many :challenges, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }

  has_attached_file :avatar, styles: { :medium => "640x" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_challenge, only: [:show, :edit, :update, :destroy, :challenger]
  before_action :owned_challenge, only: [:destroy]

  def index
    # @challenges = Challenge.all
    # @challenges = Kaminari.paginate_array(@challenges).page(params[:page]).per(5)
    @challenges = Challenge.all.order('created_at DESC').page params[:page]
  end

  def show
  end

  def new
    @challenge = current_user.challenges.build
  end

  def challenger
  end


  def create
    @challenge = current_user.challenges.build(challenge_params)

    if @challenge.save
      flash[:success] = "Your challenge has been created"
      redirect_to root_path
    else

      flash[:alert] = "Something went wrong?!? Check your form yo'!"
      render :new
    end
  end

  def edit
  end


  def update

    if @challenge.update(challenge_params)
        ChallengeMailer.challenge_email(@challenge).deliver_now
        flash[:success] = "Post updated."
        redirect_to root_path
      else
        flash[:alert] = "Update failed.  Please check the form."
        render :edit
      end

  end

  def destroy
    @challenge.destroy
    redirct_to root_path
  end

  private

  def challenge_params
    params.require(:challenge).permit(:image, :title, :description, :criteria, :challenger_id)
  end

  def set_challenge
    @challenge = Challenge.find(params[:id])
  end

  def owned_challenge
    unless current_user == @challenge.user
      flash[:alert] = "That challenge doesn't belong to you!"
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_challenge

  def destroy
    @comment = @challenge.comments.find(params[:id])

    if @comment.user_id == current_user.id
     @comment.delete
     respond_to do |format|
       format.html { redirect_to root_path }
       format.js
     end
   end
  end

  def create
    @comment = @challenge.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = "You commented the hell out of that challenge!"
      respond_to do |format|
       format.html { redirect_to root_path }
       format.js
      end
    else
      flash[:alert] = "Check the comment form, something went horribly wrong."
      render root_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_challenge
    @challenge = Challenge.find(params[:challenge_id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]

  def show
    @user = User.find_by! user_name: params[:user_name]
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

  def set_user

    if params[:user_name]
      @user = User.find_by! user_name: params[:user_name]
    else
      @user = User.find_by! id: params[:id]
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def profile_avatar_select(user)
      return image_tag user.avatar.url(:medium),
                       id: 'image-preview',
                       class: 'img-responsive img-circle profile-image' 
             image_tag 'default_friend.png', id: 'image-preview',
                                      class: 'img-responsive img-circle profile-image'

  end

end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/challenges/_challenge.html.haml
.challenges-wrapper
  .challenge
    = render 'clayout', challenge: challenge
    .challenge-bottom
      .title
        .title-content
          .user-name
            =link_to challenge.user.user_name, profile_path(challenge.user.user_name)
          = challenge.title
      .comments{id: "comments_#{challenge.id}"}
        - if challenge.comments
          = render challenge.comments.first(5), challenge: challenge

app/views/challenges/_challengerlayout.html.haml
.challenge-head
  .title
    = challenge.title
  .time-ago
    = time_ago_in_words challenge.created_at
.challenge-body
  .col-md-5
    .creator
      .image
        = link_to (image_tag challenge.user.avatar.url(:medium), class:'image'), profile_path(challenge.user.user_name)
      .text
        = challenge.user.user_name
  .versus.col-md-2
    =image_tag "vs.png", class: "versus"
  .col-md-5
    .challenger
      .image
        = image_tag User.find(challenger_id).avatar.url(:medium), class:'image'
      .text
        = User.find(challenger_id).user_name

app/views/challenges/_challenges.html.haml
= render @challenges

app/views/challenges/_clayout.html.haml
= link_to challenge_path(challenge), style: "text-decoration:none" do
  .challenge-head
    .title
      = link_to challenge.title, challenge_path(challenge), style: "text-decoration:none"
    .time-ago
      = time_ago_in_words challenge.created_at

.challenge-body
  .col-md-5
    .creator
      .image
        = link_to (image_tag challenge.user.avatar.url(:medium), class:'image'), profile_path(challenge.user.user_name)
      .text
        = challenge.user.user_name
  .versus.col-md-2
    =image_tag "vs.png", class: "versus"
  .col-md-5
    = current_user.id
    = challenge.challenger_id
    -if !challenge.challenger_id?
      .challenger
      = link_to image_tag('qm.png', class:'image'), challenger_path(challenge)
    -else
      .challenger
        .image
          = link_to (image_tag User.find(challenge.challenger_id).avatar.url(:medium), class:'image'), profile_path(User.find(challenge.challenger_id).user_name)

        .text
          = User.find(challenge.challenger_id).user_name
    

app/views/challenges/_form.html.haml
.form-wrapper
  .container
    .col-md-1
    .col-md-5
      = link_to (image_tag User.find(current_user.id).avatar.url(:medium), class: "img-responsive")
    .col-md-1
    .col-md-5
      = simple_form_for @challenge, html: { class: "form-horizontal", multipart: true } do |f|
        .form-group.text-center
          = f.input :title, label: "Title for your Challenge"
        .form-group.text-center
          = f.input :description, label: "What is it? What do you have to do?"
        .form-group.text-center
          = f.input :criteria, label: "What's the acceptance criteria?"
        .form-group.text-center
          = f.button :submit, class: 'btn btn-lg btn-success'
          = link_to "Nah...", root_path, type: :reset, class: 'btn btn-lg btn-danger'

app/views/challenges/challenger.html.haml
= render 'challengerlayout', challenge: @challenge, challenger_id: current_user.id
.text-center
  .form-wrapper
    = simple_form_for @challenge, html: { class: 'form-horizontal', multipart: true } do |f|
      = hidden_field :challenge, :challenger_id, :value => current_user.id
      .col-md-1
      .form-group.col-md-6
        .form-group.text-center
          = f.text_area :criteria, class: "form-control", placeholder: "What is/are your proposed acceptance criteria?"
        .form-group.text-center
          = f.button :submit, class: 'btn-success'
          = link_to "Nope", root_path, type: :reset, class: "btn btn-lg btn-danger"

app/views/challenges/edit.html.haml
.text-center
  = image_tag @challenge.image.url(:medium)
  = render 'form'
  - if @challenge.user.id == current_user.id
    .text-center.edit-links
      = link_to "Cancel", root_path
      |
      = link_to "Edit Challenge", edit_challenge_path(@challenge)
  - else
    .text-center.edit-links
      = link_to "Cancel", root_path

app/views/challenges/index.html.haml
.container-fluid
  = image_tag('cta_two.png', class: "img img-responsive");
  -@challenges.each do |challenge|
    = render 'challenge', challenge: challenge

  = paginate @challenges

app/views/challenges/new.html.haml
= render 'form'
.text-center.edit-links
  = link_to "cancel", root_path

app/views/challenges/show.html.haml
= render 'challenge', challenge: @challenge
.challenge-bottom
  .title
    .title-content
      .user-name
        =link_to @challenge.user.user_name, profile_path(@challenge.user.user_name)
      = @challenge.title
  .comments{id: "comments_#{@challenge.id}"}
    - if @challenge.comments
      = render @challenge.comments, challenge: @challenge
.comment-like-form.row
  .like-button.col-sm-1
    %span(class="glyphicon glyphicon-heart-empty")
  .comment-form.col-sm-11
    = form_for ([@challenge, @challenge.comments.build]) do |f|
      = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{@challenge.id}"

- if @challenge.user.id == current_user.id
  .text-center.edit-links
    = link_to "Cancel", root_path
    |
    = link_to "Edit Challenge", edit_challenge_path(@challenge)
- else
  .text-center.edit-links
    =link_to "Cancel", root_path

app/views/comments/_comment.html.haml
#comment
  .user-name
    = link_to comment.user.user_name, profile_path(comment.user.user_name)
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to challenge_comment_path(challenge, comment), method: :delete, data: {challenge_id: challenge.id, value: challenge.comments.count, confirm: "Are you sure?" }, remote: true, id: "delete-#{comment.id}", class: "delete-comment" do
      %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/create.js.erb
$('#comments_<%= @challenge.id %>').append("<%=j render 'comments/comment', challenge: @challenge, comment: @comment %>");
$('#comment_content_<%= @challenge.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @challenge.id %>').html("<%= j render @challenge.comments, challenge: @challenge, comment: @comment %>");

app/views/comments/index.html.haml
= render @comments, challenge: @challenge

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid.navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand
        = link_to root_path do
          %span.first Skin
          %span.second in the
          %span.third Game
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "New Challenge", new_challenge_path
          %li
            = link_to "Profile", profile_path(current_user.user_name)
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path

app/views/layouts/application.html.haml
%html
  %head
    %title Skin in the Game
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Archivo|Baloo+Da|Chango|Cutive+Mono|Della+Respira|Emblema+One|Fascinate|Holtwood+One+SC|Marko+One|Mitr|Pavanam|Pompiere|Stint+Ultra+Expanded|Stoke|Waiting+for+the+Sunrise", media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
%body
  = render 'layouts/navbar'

  .container-fluid
    -flash.each do |name, msg|
      = content_tag :div, msg, class: [:alert, alert_for(name)]
    = yield

app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = simple_form_for @user, url: {action: "update"}, html: { multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle.avatar-image
                  = profile_avatar_select(@user)
                = f.input :avatar, label: false,
                                   input_html: { onChange: 'loadFile(event)' }
          .row
            .col-md-12
              .form-group.text-center
                %h4 Update your bio:
                = f.input :bio, label: false, input_html: { rows: 4 }
          .form-group.text-center
            = f.button :submit, 'Update Profile', class: 'btn btn-success'

app/views/profiles/show.html.haml
.challenges-wrapper
  .row.profile-header
    .col-md-6
      .img-circle
        = image_tag @user.avatar.url(:medium), class:'image'
    .col-md-6
      .user-name-and-follow
        %h3.profile-user-name
          = @user.user_name
        %span
          - if @user == current_user
            = link_to 'Edit Profile', edit_profile_path(@user.user_name),
                                      class: 'btn edit-button'
      %p.profile-bio
        = @user.bio
      .user-statistics
        %p
          = pluralize @user.challenges.count, 'challenge'